-- This is an example Hyprland config file.
--
-- Refer to the wiki for more information.

--
-- Please note not all available settings / options are set here.
-- For a full list, see the wiki
--

-- See https://wiki.hyprland.org/Configuring/Monitors/
--monitor=,preferred,auto,auto
--monitor=,preferred,auto,2
--monitor=eDP-1,preferred,auto,1.60

-- Use the AMD card for the display, Nvidia as secondary
--env = AQ_DRM_DEVICES,/dev/dri/by-path/pci-0000:05:00.0-card:/dev/dri/by-path/pci-0000:01:00.0-card
--env = AQ_DRM_DEVICES,/dev/dri/card0:/dev/dri/card1
-- Keep these for general compatibility
--env = XDG_CURRENT_DESKTOP,Hyprland
--env = XDG_SESSION_TYPE,wayland
--env = XDG_SESSION_DESKTOP,Hyprland
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")
hl.env("LIBVA_DRIVER_NAME", "nvidia")
--monitor=,2400x1080@60,auto,1
hl.monitor({
    output = "eDP-1",
    mode = "2560x1600@120.01Hz",
    position = "0x0",
    scale = "1",
})

--monitor = eDP-1, preferred, auto, 1
--monitor = , preferred, auto, 1
--monitor=,1920x1080@60,auto,1.33

local terminal = "ghostty"
local menu = "wofi --show drun -I -m"

hl.curve("wind", { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1.05 } } })
hl.curve("winIn", { type = "bezier", points = { { 0.1, 1.1 }, { 0.1, 1.1 } } })
hl.curve("winOut", { type = "bezier", points = { { 0.3, -0.3 }, { 0, 1 } } })
hl.curve("liner", { type = "bezier", points = { { 1, 1 }, { 1, 1 } } })
hl.animation({
    leaf = "windows",
    enabled = true,
    speed = 2,
    bezier = "wind",
    style = "slidevert",
})
hl.animation({
    leaf = "windowsIn",
    enabled = true,
    speed = 2,
    bezier = "winIn",
    style = "slidevert",
})
hl.animation({
    leaf = "windowsOut",
    enabled = true,
    speed = 2,
    bezier = "winOut",
    style = "slidevert",
})
hl.animation({
    leaf = "windowsMove",
    enabled = true,
    speed = 2,
    bezier = "wind",
    style = "slide",
})
hl.animation({
    leaf = "border",
    enabled = true,
    speed = 1,
    bezier = "liner",
})
hl.animation({
    leaf = "borderangle",
    enabled = true,
    speed = 20,
    bezier = "liner",
    style = "loop",
})
hl.animation({
    leaf = "fade",
    enabled = true,
    speed = 10,
    bezier = "default",
})
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 2,
    bezier = "wind",
})

hl.device({
    name = "epic-mouse-v1",
    sensitivity = -0.5,
})

hl.window_rule({
    name = "steam-ws3",
    match = {
        initial_class = "^steam$",
    },
    workspace = "3 silent",
})

hl.window_rule({
    name = "gamesteam",
    match = {
        initial_class = "^steam_app_.*$",
    },
    workspace = "5",
})

hl.window_rule({
    name = "chromium-ws2",
    match = {
        class = "^chromium$",
    },
    workspace = "2 silent",
})


hl.window_rule({
    name = "discord-ws6",
    match = {
        class = "^discord$",
    },
    workspace = "6 silent",
})


local mainMod = "SUPER"

hl.bind(mainMod .. " + U", hl.dsp.exec_cmd("wofi-emoji"))
hl.bind(mainMod .. " + B", hl.dsp.exec_cmd("killall -9 waybar 2>/dev/null; waybar &"))
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen({ mode = "maximized", action = "toggle" }))
hl.bind(mainMod .. " + L", hl.dsp.exec_cmd("hyprlock"))
hl.bind(mainMod .. " + Return", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + C", hl.dsp.window.close())
hl.bind(mainMod .. " + M", hl.dsp.exec_cmd("hyprshutdown ; hyprctl dispatch exit"))
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + R", hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + J", hl.dsp.layout("togglesplit"))
hl.bind(mainMod .. " + X", hl.dsp.exec_cmd("prime-run steam"))
hl.bind(mainMod .. " + TAB", hl.dsp.focus({workspace = "e+1"}))
hl.bind(mainMod .. " + left", hl.dsp.focus({ workspace = "e-1" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + left", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down", hl.dsp.focus({ direction = "down" }))

hl.bind(mainMod .. " + 1", hl.dsp.focus({ workspace = 1 }))
hl.bind(mainMod .. " + 2", hl.dsp.focus({ workspace = 2 }))
hl.bind(mainMod .. " + 3", hl.dsp.focus({ workspace = 3 }))
hl.bind(mainMod .. " + 4", hl.dsp.focus({ workspace = 4 }))
hl.bind(mainMod .. " + 5", hl.dsp.focus({ workspace = 5 }))
hl.bind(mainMod .. " + 6", hl.dsp.focus({ workspace = 6 }))
hl.bind(mainMod .. " + 7", hl.dsp.focus({ workspace = 7 }))
hl.bind(mainMod .. " + 8", hl.dsp.focus({ workspace = 8 }))
hl.bind(mainMod .. " + 9", hl.dsp.focus({ workspace = 9 }))
hl.bind(mainMod .. " + 0", hl.dsp.focus({ workspace = 10 }))

hl.bind(mainMod .. " + SHIFT + 1", hl.dsp.window.move({ workspace = 1 }))
hl.bind(mainMod .. " + SHIFT + 2", hl.dsp.window.move({ workspace = 2 }))
hl.bind(mainMod .. " + SHIFT + 3", hl.dsp.window.move({ workspace = 3 }))
hl.bind(mainMod .. " + SHIFT + 4", hl.dsp.window.move({ workspace = 4 }))
hl.bind(mainMod .. " + SHIFT + 5", hl.dsp.window.move({ workspace = 5 }))
hl.bind(mainMod .. " + SHIFT + 6", hl.dsp.window.move({ workspace = 6 }))
hl.bind(mainMod .. " + SHIFT + 7", hl.dsp.window.move({ workspace = 7 }))
hl.bind(mainMod .. " + SHIFT + 8", hl.dsp.window.move({ workspace = 8 }))
hl.bind(mainMod .. " + SHIFT + 9", hl.dsp.window.move({ workspace = 9 }))
hl.bind(mainMod .. " + SHIFT + 0", hl.dsp.window.move({ workspace = 10 }))

hl.bind(mainMod .. " + S", hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))

hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag())
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize())

hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl set +5%"))
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl set 5%-"))

hl.bind("XF86AudioPlay", hl.dsp.exec_cmd(
    "playerctl play-pause; sleep 0.1; s=$(playerctl status 2>/dev/null); if [ \"$s\" = \"Playing\" ]; then notify-send -u low -t 1500 '▶ Playing' \"$(playerctl metadata --format '{{ artist }} — {{ title }}')\"; else notify-send -u low -t 1500 '⏸ Paused' \"$(playerctl metadata --format '{{ artist }} — {{ title }}')\"; fi"
))


hl.bind(mainMod .. " + Left", hl.dsp.window.resize({ x = -50, y = 0, relative = true }))
hl.bind(mainMod .. " + Right", hl.dsp.window.resize({ x = 50, y = 0, relative = true }))

hl.bind(mainMod .. " + Down", hl.dsp.window.resize({ x = 0, y = -50, relative = true }))
hl.bind(mainMod .. " + Up", hl.dsp.window.resize({ x = 0, y = 50, relative = true }))

hl.config({
    xwayland = {
        force_zero_scaling = true,
    },
    --env = LIBVA_DRIVER_NAME,nvidia
    --env = __GLX_VENDOR_LIBRARY_NAME,nvidia
    --env = ELECTRON_OZONE_PLATFORM_HINT,auto  # Reduces Electron app flickering
    -- Execute your favorite apps at launch
    --exec-once = protonvpn-app
    --exec-once = discord --start-minimized
    --exec-once = $HOME/.config/hypr/scripts/waybar_auto_hide 
    -- Source a file (multi-file configs)
    -- source = ~/.config/hypr/myColors.conf
    -- Set programs that you use
    -- Volume and Media Control
    -- Some default env vars.
    --env = QT_QPA_PLATFORMTHEME,qt5ct # change to qt6ct if you have that
    --env = SDL_VIDEODRIVER,x11
    --env = WLR_DRM_DEVICES,/dev/dri/card1
    -- For all categories, see https://wiki.hyprland.org/Configuring/Variables/
    input = {
        kb_layout = "us",
        follow_mouse = 1,
        scroll_factor = 1.0, -- FIX for broken scrolling/clicks
        touchpad = {
            natural_scroll = true,
            tap_to_click = true,
        },
        repeat_delay = 300,
        repeat_rate = 60,
        sensitivity = 0,
    },
    general = {
        -- See https://wiki.hyprland.org/Configuring/Variables/ for more
        gaps_in = 5,
        gaps_out = 6,
        border_size = 0,
        col = {
            active_border = { colors = { "rgb(fcba03)", "rgb(fcba03)" }, angle = 45 },
            inactive_border = "rgba(000000aa)",
        },
        layout = "dwindle",
        -- Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
        allow_tearing = true,
    },
    decoration = {
        -- See https://wiki.hyprland.org/Configuring/Variables/ for more
        rounding = 6,
        blur = {
            enabled = false,
            size = 8,
            passes = 4,
            new_optimizations = true,
            vibrancy = 0.1696,
        },
    },
    -- ----------------------------------------------------- 
    -- ▄▀█ █▄░█ █ █▀▄▀█ ▄▀█ ▀█▀ █ █▀█ █▄░█
    -- █▀█ █░▀█ █ █░▀░█ █▀█ ░█░ █ █▄█ █░▀█
    --
    -- name "High"
    -- credit https://github.com/mylinuxforwork/dotfiles
    -- ----------------------------------------------------- 
    animations = {
        enabled = true,
    },
    dwindle = {
        -- See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more=
        preserve_split = true,
    },
    gestures = {
        -- See https://wiki.hyprland.org/Configuring/Variables/ for more
    },
    misc = {
        -- See https://wiki.hyprland.org/Configuring/Variables/ for more
        force_default_wallpaper = 0, -- Set to 0 or 1 to disable the anime mascot wallpapers
        mouse_move_enables_dpms = true,
        key_press_enables_dpms = true,
    },
    -- Example per-device config
    -- See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more
    -- Example windowrule v1
    -- windowrule = float, ^(kitty)$
    -- Example windowrule v2
    -- windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
    -- See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
    --windowrulev2 = suppressevent maximize, class:.* # You'll probably like this.
    -- Steam
    --windowrule = match:class cs2, immediate yes
    --windowrule = match:class steam_app_298110, fullscreen yes
    --windowrule = match:class steam_app_298110, immediate yes
    --windowrule = nofocus, class:^(FarCry4\.exe)$
    --windowrule = immediate, class:^(FarCry4\.exe)$
    --windowrule = fullscreen, class:^(FarCry4\.exe)$
    -- noanim isn't necessary but animations with these rules might look bad. use at your own discretion.
    --windowrule = immediate, class:^(cs2)$
    -- See https://wiki.hyprland.org/Configuring/Keywords/ for more
    -- Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
    --bind = $mainMod, X,exec, env GDK_SCALE=1 GDK_DPI_SCALE=1.4 prime-run steam -noverifyfiles -norepairfiles -offline --force-device-    scale-factor=1.4 
    -- Go to next orkspace
    -- Move focus with mainMod + arrow keys
    -- Switch workspaces with mainMod + [0-9]
    -- Move active window to a workspace with mainMod + SHIFT + [0-9]
    -- Example special workspace (scratchpad)
    -- Scroll through existing workspaces with mainMod + scroll
    -- Move/resize windows with mainMod + LMB/RMB and dragging
    -- --- Resize active uindow ---
    -- Shrink/expand width
    -- Shrink/expand height
})

hl.on("hyprland.start", function()
    hl.exec_cmd("pgrep -x hypridle || hypridle")
    hl.exec_cmd("pgrep -x waybar || waybar")
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("chromium")
    hl.exec_cmd("prime-run steam")
    hl.exec_cmd("/usr/lib/polkit-kde-authentication-agent-1 &")
    hl.exec_cmd("sunsetr")
    end)

